### ISSUE TITLE
Re-release mockwebserver with the updated okhttp dependency

### ISSUE THREAD

**Issue by LesterTheTester** [fabric8io/mockwebserver#27]
Dependency on OKHTTP was updated to 3.10.0, but no new version has been released. For projects that are using 3.10.0 elsewhere, there is a breaking change from 3.9.1...the method signature of RealWebSocket in OKHTTP mockwebserver has changed, so you'll get

java.lang.NoSuchMethodError: No direct method <init>(Lokhttp3/Request;Lokhttp3/WebSocketListener;Ljava/util/Random;)V in class Lokhttp3/internal/ws/RealWebSocket; or its super classes

Can we please re-roll a new version with okhttp 3.10 so we don't have to mess with our transitive gradle dependencies? Thank you.

**Comment by LesterTheTester** [comment]
It also seems that there's some bugs around the implementation change of websockets in mockwebserver, which leads to queued messages all being dispatched at once. I may look into it, but it seems like this project might be abandoned and I might be better off using MWS directly.

**Comment by rohanKanojia** [comment]
I think we should proceed with releasing `0.1.1` once #31 gets merged

**Comment by rohanKanojia** [comment]
mockwebserver 0.1.1 has been released with okhttp 3.12.1. I think we can close this
