### ISSUE TITLE
Update version of mockwebserver to 4.7.2

### ISSUE THREAD

**Issue by hemanthrough** [fabric8io/mockwebserver#53]

**Comment by rohanKanojia** [comment]
@hemanthrough : Hi, Would you like to submit a PR for this? Isn't okhttp 4.x versions based in kotlin? Do you think that can break some stuff?

**Comment by hemanthrough** [comment]
Hi @rohanKanojia 

I tested locally by updating [4.8.0](https://mvnrepository.com/artifact/com.squareup.okhttp3/mockwebserver/4.8.0). The test cases seems to go through. I tested the same in a sample project. The sample seems to work fine.

However I am not very sure if this might break anything.

I could raise a PR for the same.

**Comment by jakubparysz** [comment]
Hi any update on this?

**Comment by rohanKanojia** [comment]
ah, sorry. No update. Is this change really needed?

**Comment by jakubparysz** [comment]
Hi, yes it would be good to have 4.9.0. I am using 4.9.0 okhttp in my project and when I try to run test with your library I am getting an error java.lang.NoSuchMethodError: No static method initializeInstanceForTests()V in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' because 4.9.0 does not contain this code.

**Comment by hemanthrough** [comment]
Yes I face similar issues as well. I had to downgrade my okhttp version due to this 
Issue

**Comment by snodnipper** [comment]
I had to updated the dependencies for myself.  Happy to raise a PR if helpful.
https://github.com/snodnipper/mockwebserver/tree/f92f50e7e0513f7188f2078f168ec2c25c8db28b

**Comment by rohanKanojia** [comment]
@snodnipper : Thanks for sharing, I think you can go ahead and create a PR. I think we should be able to cut a 4.x release based on 4.x version of okhttp

**Comment by msesma** [comment]
Could you also update the version with okhttp3 to 3.14.9? It is crashing with latest okhttp3

**Comment by msesma** [comment]
Never mind, importing mock web server 4.9.1 fixes the issue.

**Comment by testifyqa** [comment]
Any updates on this please? Would be great to have an official version with OkHttp v4 (e.g. 4.9.1) rather than have to fork, update and manage ourselves etc.
